---

- name: Copy systemd service to renew Let's Encrypt certs
  template: src=renew-letsencrypt.service.j2 dest=/etc/systemd/system/renew-letsencrypt.service mode=0644 owner=root group=root
  register: letsencrypt_service

- name: Copy systemd timer to renew Let's Encrypt certs
  copy: src=renew-letsencrypt.timer dest=/etc/systemd/system/renew-letsencrypt.timer mode=0644 owner=root group=root
  register: letsencrypt_timer

# need to reload to pick up service/timer changes
- name: Reload systemd daemon
  command: /bin/systemctl daemon-reload
  when: letsencrypt_service|changed or letsencrypt_timer|changed

- name: Start and enable systemd timer to renew Let's Encrypt certs
  service: name=renew-letsencrypt.timer state=started enabled=yes

- name: Download certbot
  get_url: dest={{ letsencrypt_certbot_dest }} url=https://dl.eff.org/certbot-auto mode=700

# dependencies certbot checks for on its first run
# taken from running certbot right after a clean Ubuntu 16.04 install
- name: Install certbot dependencies (Ubuntu 16.04)
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - augeas-doc
    - augeas-tools
    - binutils
    - cpp
    - cpp-5
    - dialog
    - gcc
    - gcc-5
    - libasan2
    - libatomic1
    - libcc1-0
    - libcilkrts5
    - libexpat1-dev
    - libgcc-5-dev
    - libgomp1
    - libffi-dev
    - libisl15
    - libitm1
    - liblsan0
    - libmpc3
    - libmpx0
    - libpython-dev
    - libpython2.7
    - libpython2.7-dev
    - libquadmath0
    - libssl-dev
    - libtsan0
    - libubsan0
    - python-pip-whl
    - python-pkg-resources
    - python2.7-dev
    - python3-virtualenv
    - python-dev
    - python-virtualenv
    - virtualenv
    - zlib1g-dev
  tags: packages

# vim: set ts=2 sw=2:
