---
# file: web.yml

- name: Configure web servers
  hosts: web
  user: provisioning
  sudo: yes
  roles:
    - { role: common, when: ansible_distribution == 'Ubuntu' }
    - { role: mariadb, when: ansible_distribution == 'Ubuntu' }
    - { role: nginx, when: ansible_distribution == 'Ubuntu' }
    - { role: php5-fpm, when: ansible_distribution == 'Ubuntu' }
    - { role: munin, when: ansible_distribution == 'Ubuntu' }
  vars_files:
    - vars/ipsets.yml
    - "vars/{{ ansible_distribution }}.yml"

# vim: set sw=2 ts=2:
