---
# file: web.yml

- name: Configure web servers
  hosts: web
  become: yes
  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - munin
  vars_files:
    - vars/ipsets.yml

# vim: set sw=2 ts=2:
