---

# One-off playbook to change login credentials for provisioning user.
# Generate a SHA-512 password hash using python and add it in the one
# of the included variable files for the host.
#
# using python:
#   $ python -c 'import crypt; print crypt.crypt("Soylent Green Is People!", "$6$saltiness")'
#
# playbook execution:
#   $ ansible-playbook misc_plays/change_password.yml -K --limit=$host_or_group
#

- hosts: all
  user: provisioning
  sudo: yes
  vars_files:
    - "../vars/{{ ansible_distribution }}.yml"

  tasks:
    - name: Set password, shell, homedir for provisioning user
      when: provisioning_user is defined
      user: name={{ provisioning_user.name }} password={{ provisioning_user.password }} shell={{ provisioning_user.shell }} state={{ provisioning_user.state }} createhome=no

# vim: set sw=2 ts=2:
