---
# file: roles/common/handlers/main.yml

- name: reload sshd
  systemd: name={{ sshd_service_name }} state=reloaded

- name: reload sysctl
  command: sysctl -p /etc/sysctl.conf

- name: restart firewalld
  systemd: name=firewalld state=restarted

- name: restart fail2ban
  systemd: name=fail2ban state=restarted

- name: reload systemd
  systemd: daemon_reload=yes
