---
- name: Install iptables-persistent
  apt: pkg=iptables-persistent update_cache=yes

- name: Copy /etc/iptables/rules.v4
  template: src=iptables.j2 dest=/etc/iptables/rules.v4 owner=root mode=0600
  notify:
    - restart iptables-persistent
