---
#- name: Add hostname to /etc/hosts
#  lineinfile: dest=/etc/hosts insertafter=^127.0.0.1 line='127.0.1.1       {{ inventory_hostname }}'
#  tags: hostname

- import_tasks: ntp.yml
  tags: ntp

- include_tasks: packages_{{ ansible_distribution }}.yml
  tags: packages

- include_tasks: iptables_{{ ansible_distribution }}.yml
  tags: firewall

- import_tasks: sshd.yml
  tags: sshd

# containers identify as virtualization hosts, which makes this tricky, because we have actual Debian VM hosts!
- name: Reconfigure /etc/sysctl.conf
  when: ansible_virtualization_role != 'host'
  template: src=sysctl_{{ ansible_distribution }}.j2 dest=/etc/sysctl.conf owner=root group=root mode=0644
  notify:
    - reload sysctl
  tags: sysctl

- name: Reconfigure /etc/rc.local
  when: ansible_distribution == 'Ubuntu'
  template: src=rc.local_Ubuntu.j2 dest=/etc/rc.local owner=root group=root mode=0755

- name: Set I/O scheduler
  template: src=etc/udev/rules.d/60-scheduler.rules.j2 dest=/etc/udev/rules.d/60-scheduler.rules owner=root group=root mode=0644
  tags: udev

- import_tasks: ssh-keys.yml
  tags: ssh-keys

# vim: set sw=2 ts=2:
