---

- block:
  - name: Configure apt mirror
    template: src=sources.list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644

  - name: Set fact for base packages
    set_fact:
      base_packages:
        - git
        - tmux
        - iotop
        - htop
        - strace
        - cron-apt #how does this work with systemd?
        - safe-rm
        - debian-goodies
        - mosh
        - python3-pycurl # for ansible's apt_repository
        - lzop
        - vim
        - lrzip
        - unzip
        - apt-transport-https # for https support in apt

  - name: Install base packages
    apt: name={{ base_packages }} update_cache=yes

  - name: Configure cron-apt
    import_tasks: cron-apt.yml
    tags: cron-apt

  - name: Install tarsnap
    import_tasks: tarsnap.yml
  tags: packages

# vim: set sw=2 ts=2:
