---

- block:
  - name: Configure apt mirror
    template: src=sources.list.j2 dest=/etc/apt/sources.list owner=root group=root mode=0644

  - name: Set fact for base packages
    set_fact:
      base_packages:
        - git
        - tmux
        - iotop
        - htop
        - strace
        - cron-apt
        - safe-rm
        - debian-goodies
        - mosh
        - python3-pycurl # for ansible's apt_repository
        - vim
        - unzip
        - apt-transport-https # for https support in apt
        - gnupg2
        - zstd

  - name: Install base packages
    apt: name={{ base_packages }} state=present update_cache=yes cache_valid_time=3600

  - name: Configure cron-apt
    import_tasks: cron-apt.yml
    tags: cron-apt

  - name: Install tarsnap
    import_tasks: tarsnap.yml
  tags: packages

# vim: set sw=2 ts=2:
