---
- name: Add Tarsnap apt mirror
  template: src=tarsnap_sources.list.j2 dest=/etc/apt/sources.list.d/tarsnap.list owner=root group=root mode=0644
  register: add_tarsnap_apt_repository
  when: ansible_architecture != 'armv7l'

- name: Add GPG key for Tarsnap
  apt_key: id=0x6D97F5A4CA38CF33 url=https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc state=present
  when: ansible_distribution_release != 'buster'
  register: add_tarsnap_apt_key

# Tarsnap currently provides experimental packages for Debian 10 "buster"
# See: https://www.tarsnap.com/pkg-deb.html#experimental
- name: Add GPG key for Tarsnap experimental
  apt_key: id=0xF77F1024ECFAF293 url=https://pkg.tarsnap.com/experimental/tarsnap-EXPERIMENTAL-deb-packaging-key.asc state=present
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'buster'
  register: add_tarsnap_apt_key

- name: Update apt cache
  apt:
    update_cache: yes
  when:
    add_tarsnap_apt_key is changed or
    add_tarsnap_apt_repository is changed

- name: Install tarsnap
  apt: pkg=tarsnap cache_valid_time=3600

- name: Copy tarsnaprc
  copy: src=tarsnaprc dest=/root/.tarsnaprc owner=root group=root mode=0600

# vim: set sw=2 ts=2:
