---
- name: Add Tarsnap apt mirror
  template: src=tarsnap_sources.list.j2 dest=/etc/apt/sources.list.d/tarsnap.list owner=root group=root mode=0644
  when: ansible_architecture != 'armv7l'

- name: Add GPG key for Tarsnap
  apt_key: id=0x70BD6C50E82A9D99 url=https://pkg.tarsnap.com/tarsnap-deb-packaging-key.asc state=present

- name: Install tarsnap
  apt: pkg=tarsnap update_cache=yes

# vim: set sw=2 ts=2:
