---
- name: Install munin package
  apt: name={{ item }} state=latest
  when: ansible_os_family == "Debian"
  with_items:
    - munin

- name: Create munin configuration file
  template: src=munin.conf.j2 dest=/etc/munin/munin.conf owner=root group=root mode=0644

# vim: set ts=2 sw=2:
